#jekyll-seo-tag gem variables
title: GRN

# main text of home
name: Gonçalo Rodrigues Nunes
bio: Aspiring entrepreneur and almost Electrical and Computer Engineer. A human in the making.

# twitter summary info
description: Aspiring entrepreneur and almost Electrical and Computer Engineer. A human in the making.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: http://grn.pt

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
analytics-google: 'UA-90374249-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, set to false
disqus: false

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: GoncaloRN
# google: mygoogle
instagram: GoncaloRodriguesNunes
# pinterest: mypinterest
linkedin: GoncaloRodriguesNunes
#youtube: myyoutube
#spotify: myspotify
#github: Gorbyy
#stackoverflow: 7044681/mystackoverflow
#quora: userquora
#reddit: username
#medium: GoncaloRN
#vimeo: myvimeo
email: goncalo@grn.pt

authors:
    goncalo:
        name: Gonçalo Rodrigues Nunes
        bio: Aspiring entrepreneur and almost Electrical and Computer Engineer. A human in the making.
        external-image: false
        picture: assets/images/profile.jpg
        twitter: GoncaloRN

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
paginate: 5
paginate_path: ":num/"

# if you don't need projects, comment the *projects* configs below
# projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# show next & prev links in blog post?
blog-nav-links: true

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: false

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
